### ISSUE TITLE
Can revision 3 of the engine.io protocol support?

### ISSUE THREAD

**Issue by RyannnnnWong** [1c3t3a/rust-socketio#189] opened 2022-05-22 07:06 UTC
I need revision 3 of the engine.io protocol support. because i am using the server that uses revision 3 of the engine.io protocol.

**Comment by 1c3t3a** [comment] 2022-05-22 12:25
This is an open issue at the repository, see #132 (socket.io 2x is effectively using engine.io rev 3). I appreciate any contribution and I am happy to guide everyone who wants to tackle this. However I don't currently find the time to implement this, I hope you understand that. If you plan on contributing this, I can provide you with my ideas, just comment here or send me an email.

**Comment by 1c3t3a** [comment] 2022-05-22 12:26
I'm going to close this issue as it is a duplicate of issue 132.

**Closed by 1c3t3a** 2022-05-22 12:26 UTC
