### ISSUE TITLE
Server support

### ISSUE THREAD

**Issue by t0msk** [1c3t3a/rust-socketio#337] opened 2023-06-15 10:59 UTC
Hello, will be there SocketIO server support in Rust?

**Comment by Dorbmon** [comment] 2023-06-16 08:27
Same question here :)

**Comment by 1c3t3a** [comment] 2023-06-16 08:31
This is a duplicate of #32. I would love to see a server implementation but currently don't find time to add that. I am happy to accept contributions and would be open to guide through the implementation.

Closing this as duplicate!

**Closed by 1c3t3a** 2023-06-16 08:31 UTC
